import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { CommandoHeader } from "@/components/btd/CommandoHeader";
import { ICONS, PixelIcon } from "@/components/btd/PixelIcon";
export const Route = createFileRoute("/ranger")({head:()=>({meta:[{title:"Ranger — Survive the market | BTD Commando"}]}),component:RangerPage});
const lessons = [
 {id:"competence",author:"Warren Buffett",title:"Know the edge of your map",lesson:"Evaluate businesses within your circle of competence. Knowing the limits of your understanding matters more than having an opinion on every company.",drill:"Explain how the business earns money, what could damage it, and which facts you cannot yet verify.",source:"Berkshire Hathaway · 1996 shareholder letter",url:"https://www.berkshirehathaway.com/letters/1996.html"},
 {id:"leverage",author:"Warren Buffett",title:"Do not let debt force your retreat",lesson:"Large price declines can happen unexpectedly. Borrowing to own stocks adds financial pressure and can disturb decision-making during a fall.",drill:"Stress-test the position without assuming a quick rebound. Identify any margin call, debt payment, or cash need that could force a sale.",source:"Berkshire Hathaway · 2017 shareholder letter, p. 10",url:"https://www.berkshirehathaway.com/letters/2017ltr.pdf"},
 {id:"homework",author:"Peter Lynch",title:"Recon before commitment",lesson:"A tip is not due diligence. Investigate the company, its earnings and financial position instead of blaming market machinery after an unresearched purchase.",drill:"Before a paper entry, read the financial statements and list evidence for the thesis and evidence against it.",source:"PBS FRONTLINE · Peter Lynch interview",url:"https://www.pbs.org/wgbh/pages/frontline/shows/betting/pros/lynch.html"},
 {id:"declines",author:"Peter Lynch",title:"Expect rough terrain",lesson:"Market declines are part of investing, but their timing is not reliably predictable. Preparation matters more than trying to call every market turn.",drill:"Decide how much volatility you can tolerate and what business evidence would invalidate your thesis before prices move.",source:"PBS FRONTLINE · Peter Lynch interview",url:"https://www.pbs.org/wgbh/pages/frontline/shows/betting/pros/lynch.html"}
];
const checks = ["I can explain the thesis and its uncertainties.","I checked leverage, liquidity and concentration.","I defined what would invalidate the thesis.","I can withstand the loss without relying on a rebound.","I am not treating a famous investor or a whale as an order."];
function RangerPage(){const [filter,setFilter]=useState("All");const [checked,setChecked]=useState<boolean[]>(checks.map(()=>false));const [loss,setLoss]=useState("20");const n=Number(loss);const valid=loss.trim()!==""&&Number.isFinite(n)&&n>=0&&n<=100;const recovery=valid&&n<100?n/(100-n)*100:null;const completed=checked.filter(Boolean).length;
 return <main className="min-h-screen bg-background"><CommandoHeader active="ranger" status={<span>Survival school · sourced lessons · no trade orders</span>}/><div className="mx-auto max-w-[1400px] space-y-5 px-4 py-6">
 <section className="mil-panel grid gap-5 p-5 sm:grid-cols-[1fr_auto]"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">RANGER / CAPITAL SURVIVAL</p><h1 className="pixel-title mt-2 text-3xl sm:text-4xl">Stay in the game.</h1><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Survival skills and research discipline inspired by Peter Lynch and Warren Buffett. Learn the principles, then do your own recon. Hunter follows large transfers; Ranger protects your decision process.</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/hunter" className="mil-tab">Open Hunter</Link><Link to="/sergeant" className="mil-tab">Paper discipline</Link></div></div><div className="flex items-center gap-3 border border-primary/30 bg-surface p-4"><PixelIcon name={ICONS.idle} alt="Ranger survival training emblem" className="pixel h-20 w-20 object-contain"/><div><p className="pixel-title text-primary">SURVIVE FIRST</p><p className="mt-1 text-xs text-muted-foreground">No guru signals.<br/>No guaranteed returns.</p></div></div></section>
 <section className="mil-panel p-5"><h2 className="text-xl font-bold">Field manual · lessons from the greats</h2><p className="mt-2 text-xs text-muted-foreground">Our summaries are paraphrases, not direct quotations or endorsements. The drills are BTD educational adaptations, not instructions attributed to the authors. Source links open the original material.</p><div className="my-4 flex flex-wrap gap-2">{["All","Warren Buffett","Peter Lynch"].map(x=><button key={x} type="button" aria-pressed={filter===x} className={"mil-tab "+(filter===x?"mil-tab-active":"")} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="grid gap-4 md:grid-cols-2">{lessons.filter(x=>filter==="All"||x.author===filter).map(x=><article key={x.id} className="border border-border bg-surface p-4"><p className="text-xs font-bold uppercase tracking-wider text-primary">{x.author}</p><h3 className="mt-2 text-lg font-bold">{x.title}</h3><p className="mt-2 text-sm text-muted-foreground">{x.lesson}</p><div className="mt-4 border-l-2 border-primary pl-3"><p className="text-xs font-bold">BTD FIELD DRILL</p><p className="mt-1 text-sm">{x.drill}</p></div><a href={x.url} target="_blank" rel="noopener noreferrer" className="mt-4 block text-xs text-primary underline">Read source: {x.source}</a></article>)}</div></section>
 <div className="grid gap-5 lg:grid-cols-2"><section className="mil-panel space-y-3 p-5"><h2 className="text-xl font-bold">Pre-mission survival check</h2><p className="text-xs text-muted-foreground">Session-only checklist. Not a recommendation, readiness score, or trade approval.</p>{checks.map((x,i)=><label key={x} className="flex items-start gap-3 border border-border p-3 text-sm"><input type="checkbox" checked={checked[i]} onChange={e=>setChecked(old=>old.map((v,j)=>j===i?e.target.checked:v))} className="mt-1"/>{x}</label>)}<p role="status" className="text-sm text-primary">{completed} / {checks.length} reviewed · no execution authorization</p><button className="mil-tab" onClick={()=>setChecked(checks.map(()=>false))}>Reset checklist</button></section>
 <section className="mil-panel space-y-4 p-5"><h2 className="text-xl font-bold">Drawdown terrain</h2><p className="text-sm text-muted-foreground">A loss and the gain needed to recover are not symmetric. This is arithmetic, not a prediction.</p><label className="block text-sm">Hypothetical loss (%)<input type="number" min="0" max="100" step="1" value={loss} onChange={e=>setLoss(e.target.value)} className="mt-2 block w-full rounded border border-border bg-background p-3"/></label><div className="flex flex-wrap gap-2">{[10,20,50,80].map(v=><button key={v} className="mil-tab" onClick={()=>setLoss(String(v))}>{v}% loss</button>)}</div><div role="status" className="border border-primary/40 bg-surface p-4">{!valid?<p>Enter a loss between 0 and 100%.</p>:n===100?<p>Total loss: no finite gain can recover a zero balance without new capital.</p>:<><p className="text-xs uppercase text-muted-foreground">Gain needed to reach the starting value</p><p className="pixel-title mt-2 text-3xl text-primary">{recovery!.toFixed(1)}%</p><p className="mt-2 text-sm">From 100 to {(100-n).toFixed(1)} units; recovery assumes no fees, taxes, deposits or withdrawals.</p></>}</div><p className="text-xs text-muted-foreground">Formula: loss / (100 − loss) × 100. No position sizing or broker integration.</p></section></div>
 <footer className="border-t border-border pt-4 text-xs text-muted-foreground">RANGER · Education and research only. Investor principles are not promises of safety or profit. Historical advice is not personalized financial advice. btd_v1_0 and paper policy are unchanged.</footer>
 </div></main>;
}
