/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArmoryRouteImport } from './routes/armory'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SergeantRouteImport } from './routes/sergeant'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmoryRoute = ArmoryRouteImport.update({
  id: '/armory',
  path: '/armory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SergeantRoute = SergeantRouteImport.update({
  id: '/sergeant',
  path: '/sergeant',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/auth': typeof AuthRoute
  '/communication': typeof CommunicationRoute
  '/crypto': typeof CryptoRoute
  '/intel': typeof IntelRoute
  '/api/news': typeof ApiNewsRoute
  '/index.html': typeof IndexDothtmlRoute
  '/ops': typeof OpsRoute
  '/sergeant': typeof SergeantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/auth': typeof AuthRoute
  '/communication': typeof CommunicationRoute
  '/crypto': typeof CryptoRoute
  '/intel': typeof IntelRoute
  '/api/news': typeof ApiNewsRoute
  '/index.html': typeof IndexDothtmlRoute
  '/ops': typeof OpsRoute
  '/sergeant': typeof SergeantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/armory': typeof ArmoryRoute
  '/auth': typeof AuthRoute
  '/communication': typeof CommunicationRoute
  '/crypto': typeof CryptoRoute
  '/intel': typeof IntelRoute
  '/api/news': typeof ApiNewsRoute
  '/index.html': typeof IndexDothtmlRoute
  '/ops': typeof OpsRoute
  '/sergeant': typeof SergeantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stocks': typeof StocksRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/armory'
    | '/auth'
    | '/communication'
    | '/crypto'
    | '/index.html'
    | '/ops'
    | '/sergeant'
    | '/sitemap.xml'
    | '/stocks'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/armory'
    | '/auth'
    | '/communication'
    | '/crypto'
    | '/index.html'
    | '/ops'
    | '/sergeant'
    | '/sitemap.xml'
    | '/stocks'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/armory'
    | '/auth'
    | '/communication'
    | '/crypto'
    | '/index.html'
    | '/ops'
    | '/sergeant'
    | '/sitemap.xml'
    | '/stocks'
    | '/_authenticated/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArmoryRoute: typeof ArmoryRoute
  AuthRoute: typeof AuthRoute
  CommunicationRoute: typeof CommunicationRoute
  CryptoRoute: typeof CryptoRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  OpsRoute: typeof OpsRoute
  SergeantRoute: typeof SergeantRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StocksRoute: typeof StocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armory': {
      id: '/armory'
      path: '/armory'
      fullPath: '/armory'
      preLoaderRoute: typeof ArmoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sergeant': {
      id: '/sergeant'
      path: '/sergeant'
      fullPath: '/sergeant'
      preLoaderRoute: typeof SergeantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArmoryRoute: ArmoryRoute,
  AuthRoute: AuthRoute,
  CommunicationRoute: CommunicationRoute,
  CryptoRoute: CryptoRoute,
  IntelRoute: IntelRoute,
  ApiNewsRoute: ApiNewsRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  OpsRoute: OpsRoute,
  SergeantRoute: SergeantRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StocksRoute: StocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
