export type FeedState = "live" | "snapshot" | "degraded" | "down";
export type Flag = "ACQUIRE" | "WATCH" | "REDUCE" | "STAND DOWN";
export interface KillConfig { maxDrawdownPct:number; maxNames:number; maxSleevePct:number; globalHalt:boolean; }
export interface PaperPosition { symbol:string; name:string; assetClass:string; units:number; avgPrice:number; lastPrice:number; targetSleeve:number; openedAt:string; updatedAt:string; }
export interface SergeantBook { schemaVersion:2; formulaId:"btd_v1_0"; policyId:"sergeant_policy_v1"; cash:number; peakEquity:number; realizedPnl:number; positions:PaperPosition[]; log:unknown[]; kills:KillConfig; updatedAt:string; }
export interface BookMetrics { equity:number; positionValue:number; grossExposure:number; targetGrossPct:number; drawdownPct:number; activeNames:number; maxSingleSleevePct:number; unrealizedPnl:number; realizedPnl:number; }
export interface KillState { globalHalt:boolean; drawdown:boolean; names:boolean; sleeve:boolean; any:boolean; reasons:string[]; }
export function defaultBook(now="2026-10-07T00:00:00.000Z"): SergeantBook { return {schemaVersion:2,formulaId:"btd_v1_0",policyId:"sergeant_policy_v1",cash:100,peakEquity:100,realizedPnl:0,positions:[],log:[],kills:{maxDrawdownPct:10,maxNames:10,maxSleevePct:20,globalHalt:false},updatedAt:now}; }
export function markBook(book: SergeantBook, prices: Record<string,number>): {positions:PaperPosition[];metrics:BookMetrics;nextPeak:number} { const positions=book.positions; const positionValue=positions.reduce((s,p)=>s+p.units*p.lastPrice,0); const equity=book.cash+positionValue; return {positions,metrics:{equity,positionValue,grossExposure:equity?positionValue/equity:0,targetGrossPct:positions.reduce((s,p)=>s+p.targetSleeve*100,0),drawdownPct:book.peakEquity?Math.max(0,(book.peakEquity-equity)/book.peakEquity*100):0,activeNames:positions.length,maxSingleSleevePct:equity&&positions.length?Math.max(...positions.map(p=>p.units*p.lastPrice/equity*100)):0,unrealizedPnl:0,realizedPnl:book.realizedPnl},nextPeak:Math.max(book.peakEquity,equity)}; }
export function evaluateKills(book: SergeantBook, metrics: BookMetrics): KillState { const drawdown=metrics.drawdownPct>=book.kills.maxDrawdownPct; const names=metrics.activeNames>=book.kills.maxNames; const sleeve=metrics.maxSingleSleevePct>book.kills.maxSleevePct; const globalHalt=book.kills.globalHalt; return {drawdown,names,sleeve,globalHalt,any:drawdown||names||sleeve||globalHalt,reasons:[]}; }
